apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-swing-deployment
spec:
  selector:
    matchLabels:
      app: java-swing
  replicas: 2
  template:
    metadata:
      labels:
        app: java-swing
    spec:
      containers:
        - name: jenkins-java-swing
          image: asmabouziri/projetjavajenkins:123
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: java-swing-svc
spec:
  selector:
    app: java-swing
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  type: NodePort