apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-swing-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: java-swing
  replicas: 4
  template:
    metadata:
      labels:
        app: java-swing
    spec:
      containers:
        - name: jenkins-java-swing
          image: asmabouziri/projetjavajenkins:123
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DISPLAY
              value: " 192.168.1.39:0.0"

---
apiVersion: v1
kind: Service
metadata:
  name: java-swing-svc
  namespace: default
spec:
  selector:
    app: java-swing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
