FROM openjdk:11

# Installe Maven
RUN apt-get update && \
    apt-get install -y maven && \
    rm -rf /var/lib/apt/lists/*

# Crée le répertoire de travail
WORKDIR /app

# Copie le pom.xml et télécharge les dépendances
COPY pom.xml /app
RUN mvn dependency:copy-dependencies

# Copie les fichiers sources et le fichier JAR
COPY src /app/src
COPY target/test-jenkins-1.0-SNAPSHOT.jar /app/projetjavajenkins.jar

# Exécute l'application
ENTRYPOINT ["java", "-Djava.awt.headless=true", "-cp", "projetjavajenkins.jar:dependency/*", "main.java.SeConnecter"]
